"""
Markdown Export Module for EasyRead

Provides functionality to export Easy Read documents to Markdown format.
"""

import tempfile
from typing import Optional


def export_to_markdown(
    title: str,
    sentences: list[dict],
    include_images: bool = True,
    image_base_url: Optional[str] = None,
    output_path: Optional[str] = None,
) -> str:
    """
    Export Easy Read content to Markdown format.

    Args:
        title: Document title
        sentences: List of sentence dictionaries with keys:
            - sentence: The text content
            - image_prompt: Description of the image
            - highlighted: Whether this is a key sentence
            - image_path: Optional path to the icon image
        include_images: Whether to include image references
        image_base_url: Base URL for image references
        output_path: Optional output file path. If None, creates temp file.

    Returns:
        Path to the generated Markdown file
    """
    content = generate_markdown_content(
        title, sentences, include_images, image_base_url
    )

    if not output_path:
        with tempfile.NamedTemporaryFile(
            suffix=".md", prefix="easyread_", delete=False
        ) as tmp:
            output_path = tmp.name

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path


def generate_markdown_content(
    title: str,
    sentences: list[dict],
    include_images: bool = True,
    image_base_url: Optional[str] = None,
) -> str:
    """
    Generate Markdown content string.

    Args:
        title: Document title
        sentences: List of sentence dictionaries
        include_images: Whether to include image references
        image_base_url: Base URL for image references

    Returns:
        Markdown content as a string
    """
    lines = []

    # Title
    lines.append(f"# {title}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Sentences with images
    for item in sentences:
        sentence = item.get("sentence", "")
        highlighted = item.get("highlighted", False)
        image_prompt = item.get("image_prompt", "")
        image_path = item.get("image_path", "")

        # Add sentence (highlighted sentences are bold)
        if highlighted:
            lines.append(f"**{sentence}**")
        else:
            lines.append(sentence)

        # Add image reference if available
        if include_images and image_path:
            if image_base_url:
                image_url = f"{image_base_url}/{image_path}"
            else:
                image_url = image_path

            alt_text = image_prompt or f"Icon for: {sentence[:50]}"
            lines.append("")
            lines.append(f"![{alt_text}]({image_url})")

        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by EasyRead*")

    return "\n".join(lines)


def export_to_markdown_bytes(
    title: str,
    sentences: list[dict],
    include_images: bool = True,
    image_base_url: Optional[str] = None,
) -> bytes:
    """
    Export Easy Read content to Markdown and return as bytes.

    Args:
        title: Document title
        sentences: List of sentence dictionaries
        include_images: Whether to include image references
        image_base_url: Base URL for image references

    Returns:
        Markdown file content as bytes (UTF-8 encoded)
    """
    content = generate_markdown_content(
        title, sentences, include_images, image_base_url
    )
    return content.encode("utf-8")
